# Generated by Django 5.0 on 2025-03-26 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PostDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('media_urls', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('related_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_drafts', to='ai_agent.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_media_app.socialmedia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('post_id', models.CharField(blank=True, max_length=100, null=True)),
                ('engagement_metrics', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('post_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='social_media_app.postdraft')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_posts', to='social_media_app.socialmediaaccount')),
            ],
            options={
                'ordering': ['scheduled_time'],
            },
        ),
        migrations.AddField(
            model_name='postdraft',
            name='platforms',
            field=models.ManyToManyField(to='social_media_app.socialmediaaccount'),
        ),
    ]
