# Generated by Django 5.0 on 2025-03-26 19:54

import django.db.models.deletion
import shortuuid.main
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('text', models.TextField(null=True)),
                ('media_is_img', models.BooleanField(default=False)),
                ('media_is_vid', models.BooleanField(default=False)),
                ('media_is_aud', models.BooleanField(default=False)),
                ('media_is_doc', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='media/chatroom_msg_media')),
                ('media_is_img', models.BooleanField(default=False)),
                ('media_is_vid', models.BooleanField(default=False)),
                ('media_is_aud', models.BooleanField(default=False)),
                ('media_is_doc', models.BooleanField(default=False)),
                ('media_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_media', to='ai_agent.chat')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='media',
            field=models.ManyToManyField(blank=True, to='ai_agent.chatmedia'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=128, null=True)),
                ('group_description', models.TextField(blank=True)),
                ('group_picture', models.ImageField(blank=True, default='media/default_group_pic.png', null=True, upload_to='')),
                ('is_private', models.BooleanField(default=False)),
                ('private_group', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='chat_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='ai_agent.chatroom'),
        ),
        migrations.CreateModel(
            name='TaskWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_sequence', models.JSONField(default=dict)),
                ('task_work_flow_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_workflows', to='ai_agent.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('hubspot_contact', 'Create Hubspot Contact'), ('post_content', 'Generate Post Content'), ('schedule_post', 'Schedule Post'), ('immediate_post', 'Post Immediately'), ('audience_analysis', 'Audience Analysis'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('sequence_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('function_name', models.CharField(max_length=100)),
                ('parameters', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('task_id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_agent.taskworkflow')),
            ],
            options={
                'ordering': ['workflow', 'sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='task_workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='ai_agent.taskworkflow'),
        ),
    ]
